services:
  com3524_project:
    build: .
    image: com3524:forestfire
    container_name: com3524-container
    stdin_open: true
    tty: true
    environment:
      DISPLAY: "host.docker.internal:0.0" #windows only
    ports:
      - "5000:5000"
    volumes:
      - ./CA_tool:/src/CA_tool
      - ./CAPyle_releaseV2:/src/CAPyle_releaseV2
      - ./main:/src/main
      - ./run_tool.py:/src/run_tool.py
    command: python3 -u run_tool.py